### ISSUE TITLE
Broken indium compatibility

### ISSUE THREAD

**Issue by MenacingPerson** [IrisShaders/Iris-Installer-Files#1]
When installed, indium gives an error about sodium being required.

**Comment by MenacingPerson** [comment]
nvm, i just had an old version of indium

**Comment by MenacingPerson** [comment]
wait, it still doesn't work? Using latest indium and iris.
![image](https://user-images.githubusercontent.com/59611020/121652946-cf438000-cab9-11eb-8c34-4d8530ddb7e5.png)

**Comment by MenacingPerson** [comment]
i am using the version with the curseforge link.

**Comment by AlsoSylv** [comment]
Hi! so this is actually an indium bug, please join the iris discord for a solution, and then feel free to ping me "Niko"

**Comment by MenacingPerson** [comment]
i downloaded the iris version from github actions and it works now, i guess
